<!Doctype html>
<html lang="de-De">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Registrierung</title>
    <link rel="stylesheet" href="/style/style.css">
</head>
<body>
<h1>Registrierung</h1>
<h2>Ihre Angaben:</h2>
<form action="/register-submit" method="POST">

    <label for="fName">Vorname:</label><br>
    <input type="text" name="fName" id="fName"><br>

    <label for="lName">Nachname:</label><br>
    <input type="text" name="lName" id="lName"><br>

    <label for="email">E-Mail:</label><br>
    <input type="email" name="email" id="email"><br>

    <label for="password">Passwort:</label><br>
    <input type="password" name="password" id="password"><br>

    <label for="password2">Passwort wiederholen</label><br>
    <input type="password" name="password2" id="password2"><br>
    <button>Registrieren</button>
    <br>
    <br>
    <a href="/login">Einloggen</a>
</form>
<?php
$errors = $_SESSION['flashMessages'] ?? [];
unset($_SESSION['flashMessages']);
?>

<?php if (!empty($errors)): ?>
<div class="error-messages">

    <?php foreach ($errors as $field => $messages): ?>
        <h3><?= htmlspecialchars($field) ?></h3>
        <ul>
            <?php foreach ($messages as $msg): ?>
                <li><?= htmlspecialchars($msg) ?></li>
            <?php endforeach; ?>
        </ul>
    <?php endforeach; ?>
    </div>
<?php endif; ?>
</body>
</html>